# User.create(handle: "@fjantelo", first_name: "Fernando", last_name: "Antelo")
# User.create(handle: "@elonmusk", first_name: "Elon", last_name: "Musk")
# Tweet.create(text: "What is going on in the world today?", user_id: 1)
# Tweet.create(text: "Hello all!", user_id: 1)
# Tweet.create(text: "Crazy nonsense", user_id: 2)
# Tweet.create(text: "Something about dogecoin", user_id: 2)
